export const STAGES = ["init", "prd", "hld", "sdd", "impl", "review", "deploy", "retro"];
export const TEMPLATES = ["PRD", "ARCH", "SDD", "TEST", "REVIEW", "DEPLOY", "RETRO"];
export const PLATFORMS = ["cursor", "trae", "qoder", "codebuddy", "claude-code", "codex"];
export const PLATFORM_CHOICES = [...PLATFORMS, "all"];
// Platforms whose adapter files must live in a dot-directory at the project
// root for the tool to load them (for example Cursor only reads `.cursor/`
// at the workspace root). README-only adapters have no entry here.
export const PLATFORM_DOT_DIRS = {
  cursor: ".cursor",
  trae: ".trae",
  qoder: ".qoder",
  codebuddy: ".codebuddy"
};
export const GENERATED_HEADER = "<!-- AUTO-GENERATED BY AI-Project-Workflow -->\n";
export const LEGACY_GENERATED_HEADER = "<!-- AUTO-GENERATED BY ai-sdd. DO NOT EDIT DIRECTLY. -->\n";
export const VERSION = "0.1.0";
export const WORKFLOW_VERSION = "1.0.0";
