export const VERSION = "0.2.0";
export const WORKFLOW_VERSION = "1.0.0";
export const DEFAULT_WORKFLOW_CONFIG = Object.freeze({
  protocolVersion: WORKFLOW_VERSION,
  stages: Object.freeze([
    Object.freeze({ id: "init", title: "Initialize" }),
    Object.freeze({ id: "prd", title: "Product Requirements" }),
    Object.freeze({ id: "hld", title: "High-Level Design" }),
    Object.freeze({ id: "sdd", title: "Software Detailed Design" }),
    Object.freeze({ id: "impl", title: "Implementation" }),
    Object.freeze({ id: "review", title: "Review" }),
    Object.freeze({ id: "deploy", title: "Deployment" }),
    Object.freeze({ id: "retro", title: "Retrospective" })
  ])
});
export const STAGES = DEFAULT_WORKFLOW_CONFIG.stages.map((stage) => stage.id);
export const TEMPLATES = ["PRD", "ARCH", "SDD", "TEST", "REVIEW", "DEPLOY", "RETRO"];
export const PLATFORMS = ["cursor", "trae", "qoder", "codebuddy", "catpaw", "claude-code", "codex"];
export const PLATFORM_CHOICES = [...PLATFORMS, "all"];
// Platforms whose adapter files must live in a dot-directory at the project
// root for the tool to load them (for example Cursor only reads `.cursor/`
// at the workspace root). README-only adapters have no entry here.
export const PLATFORM_DOT_DIRS = {
  cursor: ".cursor",
  trae: ".trae",
  qoder: ".qoder",
  codebuddy: ".codebuddy",
  catpaw: ".catpaw"
};
export const GENERATED_HEADER = "<!-- AUTO-GENERATED BY AI-Project-Workflow -->\n";
export const LEGACY_GENERATED_HEADER = "<!-- AUTO-GENERATED BY ai-sdd. DO NOT EDIT DIRECTLY. -->\n";
